import { NextRequest } from 'next/server';
import {
  createApiResponse,
  createApiError,
  handleZodError,
  validateBody,
  getSupabaseClient,
  getAuthUserId,
} from '@/lib/api-utils';
import { ExportPdfSchema } from '@/lib/schemas';

function generatePdfHtml(data: {
  projectName: string;
  description: string;
  applicationType: string;
  features: string[];
  schema: Record<string, unknown>;
  includeCode: boolean;
}): string {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>${data.projectName} - Specification</title>
  <style>
    body { font-family: 'Helvetica', 'Arial', sans-serif; margin: 40px; color: #1a1a1a; }
    h1 { font-size: 24px; margin-bottom: 4px; }
    h2 { font-size: 18px; margin-top: 24px; margin-bottom: 8px; border-bottom: 2px solid #e5e7eb; padding-bottom: 4px; }
    p { font-size: 14px; line-height: 1.6; color: #4b5563; }
    ul { padding-left: 20px; }
    li { font-size: 14px; margin-bottom: 4px; color: #4b5563; }
    .meta { font-size: 12px; color: #9ca3af; margin-bottom: 24px; }
    pre { background: #f3f4f6; padding: 16px; border-radius: 8px; font-size: 11px; overflow-x: auto; white-space: pre-wrap; }
    .badge { display: inline-block; background: #3b82f6; color: white; padding: 2px 10px; border-radius: 12px; font-size: 12px; }
    @media print { body { margin: 0; } }
  </style>
</head>
<body>
  <h1>${data.projectName}</h1>
  <span class="badge">${data.applicationType}</span>
  <p class="meta">Generated by SP Associates - AI Software Solution Configurator</p>

  <h2>Description</h2>
  <p>${data.description}</p>

  <h2>Features</h2>
  <ul>
    ${data.features.map((f) => `<li>${f}</li>`).join('\n    ')}
  </ul>

  ${data.includeCode ? `<h2>Schema</h2><pre>${JSON.stringify(data.schema, null, 2)}</pre>` : ''}

  <h2>Pages</h2>
  <ul>
    ${((data.schema as any)?.pages || []).map((p: any) => `<li><strong>${p.name}</strong> — ${p.path || '/'}</li>`).join('\n    ')}
  </ul>

  <h2>Components</h2>
  <ul>
    ${((data.schema as any)?.components || []).map((c: any) => `<li>${c.type}${c.id ? ` (${c.id})` : ''}</li>`).join('\n    ')}
  </ul>
</body>
</html>`;
}

export async function POST(request: NextRequest) {
  try {
    const userId = getAuthUserId(request);
    if (!userId) {
      return createApiError({ code: 'UNAUTHORIZED', message: 'Authentication required' }, 401);
    }

    const body = await request.json();
    const data = validateBody(ExportPdfSchema, body);

    const supabase = getSupabaseClient();
    const { data: project, error: projectError } = await supabase
      .from('projects')
      .select('name, description, application_type, features')
      .eq('id', data.projectId)
      .eq('user_id', userId)
      .single();

    if (projectError || !project) {
      return createApiError({ code: 'NOT_FOUND', message: 'Project not found' }, 404);
    }

    const { data: schemaRecord, error: schemaError } = await supabase
      .from('schemas')
      .select('schema')
      .eq('id', data.schemaId)
      .single();

    if (schemaError || !schemaRecord) {
      return createApiError({ code: 'NOT_FOUND', message: 'Schema not found' }, 404);
    }

    const _pageSize = data.options?.format === 'letter' ? 'letter' : 'a4';
    const includeCode = data.options?.includeCode || false;

    const htmlContent = generatePdfHtml({
      projectName: project.name,
      description: project.description,
      applicationType: project.application_type,
      features: project.features,
      schema: schemaRecord.schema,
      includeCode,
    });

    const fileName = `${project.name.replace(/\s+/g, '-').toLowerCase()}-report.html`;

    const { data: _storageData, error: storageError } = await supabase.storage
      .from('exports')
      .upload(`${userId}/${data.schemaId}/${fileName}`, htmlContent, {
        contentType: 'text/html',
        upsert: true,
      });

    if (storageError) {
      return createApiError({ code: 'STORAGE_ERROR', message: storageError.message }, 500);
    }

    const { data: urlData } = supabase.storage
      .from('exports')
      .getPublicUrl(`${userId}/${data.schemaId}/${fileName}`);

    return createApiResponse({
      url: urlData.publicUrl,
      fileName: fileName.replace('.html', '.pdf'),
      size: new Blob([htmlContent]).size,
      expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    });
  } catch (err) {
    return handleZodError(err);
  }
}
